int *getComPort();
int serialOperation(int portNo, int baudRate, bool status);
uint16_t *getStatus(int salveId, int address, int readMode, int count);
int writeDataToRegister(int salveId, int address, int *sendCmdBuf, int count);
int clawEnable(int salveId, bool status);
int rotateEnable(int salveId, bool status);
int runWithoutParam(int salveId, int cmdId);
int runWithoutParamOfEvs(int salveId, bool status);
int rotateWithoutParam(int salveId, int cmdId);
int runWithParam(int salveId, int pos, int speed, int torque);
int runWithParamOfEvs(int salveId, int maxData, int minData, int timeout, bool status);
int runWithParamOfErg32(int salveId, int pos, int speed, int torque);
int rotateWithParam(int salveId, int angle, int speed, int torque, bool absStatus, int cycleNum);
int rotateWithParamOfErg26(int salveId, int angle, int speed, int torque);
int changeSalveId(int oldId, int newId);
int changeSalveIdOfErg32(int oldId, int newId);
int changeBaudRate(int salveId, int baudRate);
int changeBaudRateOfErg32(int salveId, int baudRate);
int clawEncoderZero(int salveId);
int switchAutoPatrolInspection(int salveId, bool status);
int getClawCurrentStatus(int salveId);
int getClawCurrentStatusOfErg32(int salveId);
int getRotateCurrentStatusOfErg32(int salveId);
int getClawCurrentLocation(int salveId);
int getClawCurrentLocationOfErg32(int salveId);
int getCurrentAbsAngleOfErg32(int salveId);
int getCurrentRelAngleOfErg32(int salveId);
int getClawCurrentSpeed(int salveId);
int getClawCurrentSpeedOfErg32(int salveId);
int getRotateCurrentSpeedOfErg32(int salveId);
int getClawCurrentTorque(int salveId);
int getClawCurrentTorqueOfErg32(int salveId);
int getRotateCurrentTorqueOfErg32(int salveId);
int getClawCurrentTemperature(int salveId);
int getClawCurrentTemperatureOfErg32(int salveId);
int getClawCurrentVoltage(int salveId);
int getClawCurrentVoltageOfErg32(int salveId);
int *querySoftwareVersion(int salveId);
int *querySoftwareVersionOfErg32(int salveId);